version: 2.1

orbs:
  bitcartcc: bitcartcc/bitcartcc-shared@1

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - bitcartcc/lint:
          name: lint
          executor: bitcartcc/python-node
          pre-steps:
            - checkout
            - bitcartcc/install-node-dependencies
      - bitcartcc/deploy-amd64:
          name: deploy-amd64
          context: global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - bitcartcc/deploy-arm:
          name: deploy-arm
          context: global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - bitcartcc/deploy:
          name: deploy
          context: global
          requires:
            - deploy-amd64
            - deploy-arm
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
