version: 2.1

orbs:
  bitcart: bitcart/bitcart-shared@2

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - bitcart/lint:
          name: lint
          executor: bitcart/python-node
          pre-steps:
            - checkout
            - bitcart/install-node-dependencies
      - bitcart/deploy-amd64:
          name: deploy-amd64
          context: global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - bitcart/deploy-arm:
          name: deploy-arm
          context: global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - bitcart/deploy:
          name: deploy
          context: global
          requires:
            - deploy-amd64
            - deploy-arm
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
